# Nginx tasks
# roles/nginx/tasks/main.yml

- name: Install NGINX
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: true

- name: Ensure web root exists
  ansible.builtin.file:
    path: "{{ web_root }}"
    state: directory
    owner: "{{ nginx_user }}"
    group: "{{ nginx_user }}"
    mode: '0750'

- name: Deploy static index.html
  ansible.builtin.copy:
    src: index.html
    dest: "{{ web_root }}/index.html"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_user }}"
    mode: '0644'

- name: Deploy nginx config
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: '0644'
  notify: restart nginx

- name: Restrict access to /etc/nginx
  ansible.builtin.file:
    path: /etc/nginx
    recurse: yes
    mode: '0750'

- name: Ensure nginx is started and enabled
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
