- name: 🛡️ Ensure /tmp/bastion.pem has correct permissions if it exists
  become: false
  copy:
    dest: /tmp/bastion.pem
    content: "{{ lookup('env', 'BASTION_PEM_KEY') }}"
    mode: '0600'
  when: lookup('env', 'BASTION_PEM_KEY') is defined and lookup('env', 'BASTION_PEM_KEY') != ''
