---
- name: Test connectivity with ping
  ping:
  register: ping_result

- name: Display ping result
  debug:
    msg: "Successfully connected to {{ inventory_hostname }}"
  when: ping_result is succeeded

- name: Display ping failure
  debug:
    msg: "Failed to connect to {{ inventory_hostname }}"
  when: ping_result is failed
