---
- name: 🧰 Bastion PEM Setup
  hosts: localhost
  gather_facts: false

  roles:
    - role: bastion_setup
      when: lookup('env', 'BASTION_PEM_KEY') is defined and lookup('env', 'BASTION_PEM_KEY') != ''
