---
- name: Install PHP on Web Servers
  hosts: web_servers
  become: true
  roles:
    - php-installer

- name: Install Redis on Redis Servers
  hosts: redis_servers
  become: true
  roles:
    - redis
