# Package installation playbook
# playbooks/package_install.yml

- name: Install Required Packages
  hosts: all
  become: true
  vars:
    install_pip: true
    install_python3: true
    install_boto3: true
    install_nodejs: true
    install_php: true
    install_nginx: false
    install_apache2: false
    install_mysql: false
    install_postgresql: false
  roles:
    - package_installer